# Generated by Django 3.1.5 on 2021-01-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'Worst'), (2, 'Not Bad'), (3, 'Good'), (4, 'Best')]),
        ),
    ]
